// <auto-generated />
namespace GCS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class splitfilterstylingintotwoprops : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(splitfilterstylingintotwoprops));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091346498_split filter styling into two props"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
