// <auto-generated />
namespace GCS.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class addcorrectedQueryfieldtosearchEntryclass : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcorrectedQueryfieldtosearchEntryclass));

        string IMigrationMetadata.Id {
            get { return "201710261006188_add correctedQuery field to searchEntry class"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
