// <auto-generated />
namespace GCS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class addfieldsclickURlandclickNodeIdtosearchentryclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfieldsclickURlandclickNodeIdtosearchentryclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201710250857388_add fields clickURl and clickNodeId to searchentry class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
