// <auto-generated />
namespace GCS.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class addfielddevelopmentURL : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfielddevelopmentURL));

        string IMigrationMetadata.Id {
            get { return "201801031210263_add field developmentURL"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
