// <auto-generated />
namespace W3S_GCS.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class addpropertykeepalias : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpropertykeepalias));

        string IMigrationMetadata.Id {
            get { return "201801180919325_add property keepalias"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
